number_1 = float(input("first number "))
number_2 = float(input("second number "))
subtraction = (number_1 - number_2)
addition = (number_1 + number_2)
multiplication =(number_1 * number_2)
division = (number_1 / number_2)
print(subtraction)
print(addition)
print(multiplication)
print(division)
